import { IMovieDetailed } from "types/movies";

export const testData: IMovieDetailed[] = [
  {
      "movie_id": 21,
      "title": "28 Years Later",
      "release_year": 2025,
      "runtime_minutes": 115,
      "rating": null,
      "box_office": "150367300.00",
      "director_id": 18,
      "country_id": 1,
      "overview": "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
      "genres": "Horror; Thriller; Science Fiction",
      "director_name": "Danny Boyle",
      "budget": "60000000",
      "studios": "Columbia Pictures; DNA Films; Decibel Films; TSG Entertainment",
      "poster_url": "https://image.tmdb.org/t/p/w500/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
      "collection": "28 Days/Weeks/Years Later Collection",
      "original_title": "28 Years Later",
      "actors": "[{\"name\":\"Jodie Comer\",\"character\":\"Isla\"},{\"name\":\"Alfie Williams\",\"character\":\"Spike\"},{\"name\":\"Aaron Taylor-Johnson\",\"character\":\"Jamie\"},{\"name\":\"Ralph Fiennes\",\"character\":\"Dr. Ian Kelson\"},{\"name\":\"Edvin Ryding\",\"character\":\"Erik Sundqvist\"},{\"name\":\"Christopher Fulford\",\"character\":\"Sam\"},{\"name\":\"Stella Gonet\",\"character\":\"Jenny\"},{\"name\":\"Chi Lewis-Parry\",\"character\":\"Samson\"},{\"name\":\"Jack O'Connell\",\"character\":\"Jimmy Crystal\"},{\"name\":\"Rocco Haynes\",\"character\":\"Young Jimmy\"}]"
  },
  {
      "movie_id": 93,
      "title": "Ad Vitam",
      "release_year": 2025,
      "runtime_minutes": 97,
      "rating": null,
      "box_office": null,
      "director_id": 89,
      "country_id": 1,
      "overview": "When he and his pregnant wife are attacked in their home, a former elite agent becomes trapped in a deadly manhunt tied to his own painful past.",
      "genres": "Thriller; Drama; Crime; Action",
      "director_name": "Rodolphe Lauga",
      "budget": null,
      "studios": "Les Films du Cap",
      "poster_url": "https://image.tmdb.org/t/p/w500/xqBSapk1nC35WlZ6PraMjOVMQBy.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/dMloNvayweggmvv0UD0iOJIkkbH.jpg",
      "collection": null,
      "original_title": "Ad Vitam",
      "actors": "[{\"name\":\"Guillaume Canet\",\"character\":\"Franck Lazareff\"},{\"name\":\"Alexis Manenti\",\"character\":\"Nico\"},{\"name\":\"Stéphane Caillard\",\"character\":\"Leo\"},{\"name\":\"Nassim Lyes\",\"character\":\"Ben\"},{\"name\":\"Zita Hanrot\",\"character\":\"Manon\"},{\"name\":\"Johan Heldenbergh\",\"character\":\"Vanaken\"},{\"name\":\"Etienne Guillou-Kervern\",\"character\":\"Stanislas Lacaze\"},{\"name\":\"Jamel Blissat\",\"character\":\"Homme DGSI 2\"},{\"name\":\"Maurice Chan\",\"character\":\"Le policier scientifique\"},{\"name\":\"Laurent Merillon\",\"character\":\"Gendarme GIGN\"}]"
  },
  {
      "movie_id": 89,
      "title": "Alarum",
      "release_year": 2025,
      "runtime_minutes": 95,
      "rating": null,
      "box_office": null,
      "director_id": 85,
      "country_id": 1,
      "overview": "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      "genres": "Action; Crime; Thriller",
      "director_name": "Michael Polish",
      "budget": "20000000",
      "studios": "BondIt Media Capital; Buffalo 8 Productions; Convergence Entertainment; Highland Film Group; Signature Entertainment; Dream Team Films; Grindstone Entertainment Group; Taurus Film; Lionsgate",
      "poster_url": "https://image.tmdb.org/t/p/w500/ckyYZf5cGTSOwF8LWIRqeThyh18.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      "collection": null,
      "original_title": "Alarum",
      "actors": "[{\"name\":\"Scott Eastwood\",\"character\":\"Joe Travers\"},{\"name\":\"Sylvester Stallone\",\"character\":\"Chester\"},{\"name\":\"Willa Fitzgerald\",\"character\":\"Lara Travers\"},{\"name\":\"Mike Colter\",\"character\":\"Orlin\"},{\"name\":\"D.W. Moffett\",\"character\":\"Ronald Burbridge\"},{\"name\":\"Isis Valverde\",\"character\":\"Bridgette Rousseau\"},{\"name\":\"Joel Cohen\",\"character\":\"Roland Rousseau\"},{\"name\":\"Mark Polish\",\"character\":\"CIA Agent Kirby\"},{\"name\":\"Anton Narinskiy\",\"character\":\"Krol\"},{\"name\":\"Patrick Millin\",\"character\":\"Dimitri\"}]"
  },
  {
      "movie_id": 52,
      "title": "A Minecraft Movie",
      "release_year": 2025,
      "runtime_minutes": 101,
      "rating": null,
      "box_office": "955149195.00",
      "director_id": 49,
      "country_id": 1,
      "overview": "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
      "genres": "Family; Fantasy; Comedy; Adventure; Action",
      "director_name": "Jared Hess",
      "budget": "150000000",
      "studios": "Warner Bros. Pictures; Legendary Pictures; Mojang Studios; Vertigo Entertainment; On the Roam; Domain Entertainment",
      "poster_url": "https://image.tmdb.org/t/p/w500/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
      "collection": "The Minecraft Movie Collection",
      "original_title": "A Minecraft Movie",
      "actors": "[{\"name\":\"Jason Momoa\",\"character\":\"Garrett\"},{\"name\":\"Jack Black\",\"character\":\"Steve\"},{\"name\":\"Sebastian Eugene Hansen\",\"character\":\"Henry\"},{\"name\":\"Emma Myers\",\"character\":\"Natalie\"},{\"name\":\"Danielle Brooks\",\"character\":\"Dawn\"},{\"name\":\"Jennifer Coolidge\",\"character\":\"Vice Principal Marlene\"},{\"name\":\"Rachel House\",\"character\":\"Malgosha (voice)\"},{\"name\":\"Allan Henry\",\"character\":\"Malgosha (Creature Performer)\"},{\"name\":\"Bram Scott-Breheny\",\"character\":\"Young Steve\"},{\"name\":\"Moana Williams\",\"character\":\"Young Garrett\"}]"
  },
  {
      "movie_id": 66,
      "title": "Another Simple Favor",
      "release_year": 2025,
      "runtime_minutes": 123,
      "rating": null,
      "box_office": null,
      "director_id": 63,
      "country_id": 1,
      "overview": "Stephanie and Emily reunite on the beautiful island of Capri, Italy for Emily's extravagant wedding to a rich Italian businessman. Along with the glamorous guests, expect murder and betrayal to RSVP for a wedding with more twists and turns than the road from the Marina Grande to the Capri town square.",
      "genres": "Comedy; Thriller; Crime",
      "director_name": "Paul Feig",
      "budget": null,
      "studios": "Feigco Entertainment; Lionsgate",
      "poster_url": "https://image.tmdb.org/t/p/w500/zboCGZ4aIqPMd7VFI4HWnmc7KYJ.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/b6e5Nss2QNoQM4wJv2VppChswNP.jpg",
      "collection": "A Simple Favor Collection",
      "original_title": "Another Simple Favor",
      "actors": "[{\"name\":\"Anna Kendrick\",\"character\":\"Stephanie Smothers\"},{\"name\":\"Blake Lively\",\"character\":\"Emily Nelson\"},{\"name\":\"Michele Morrone\",\"character\":\"Dante Versano\"},{\"name\":\"Henry Golding\",\"character\":\"Sean Townsend\"},{\"name\":\"Allison Janney\",\"character\":\"Aunt Linda McLanden\"},{\"name\":\"Elizabeth Perkins\",\"character\":\"Margaret McLanden\"},{\"name\":\"Elena Sofia Ricci\",\"character\":\"Portia Versano\"},{\"name\":\"Alex Newell\",\"character\":\"Vicky\"},{\"name\":\"Andrew Rannells\",\"character\":\"Darren\"},{\"name\":\"Taylor Ortega\",\"character\":\"Agent Irene Walker\"}]"
  },
  {
      "movie_id": 59,
      "title": "Ash",
      "release_year": 2025,
      "runtime_minutes": 95,
      "rating": null,
      "box_office": null,
      "director_id": 56,
      "country_id": 1,
      "overview": "A woman wakes up on a distant planet and finds the crew of her space station viciously killed. Her investigation into what happened sets in motion a terrifying chain of events.",
      "genres": "Horror; Science Fiction",
      "director_name": "Flying Lotus",
      "budget": null,
      "studios": "XYZ Films; Echo Lake Entertainment; GFC Films; IPR.VC; Brainfeeder Films",
      "poster_url": "https://image.tmdb.org/t/p/w500/nRa8B3tQCUK6pVwjasIyQehbvpF.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/sQa299yggIkxfwKJFgzYwDdsC9t.jpg",
      "collection": null,
      "original_title": "Ash",
      "actors": "[{\"name\":\"Eiza González\",\"character\":\"Riya\"},{\"name\":\"Aaron Paul\",\"character\":\"Brion\"},{\"name\":\"Iko Uwais\",\"character\":\"Adhi\"},{\"name\":\"Kate Elliott\",\"character\":\"Clarke\"},{\"name\":\"Beulah Koale\",\"character\":\"Kevin\"},{\"name\":\"Flying Lotus\",\"character\":\"Davis\"}]"
  },
  {
      "movie_id": 56,
      "title": "A Working Man",
      "release_year": 2025,
      "runtime_minutes": 116,
      "rating": null,
      "box_office": "99068160.00",
      "director_id": 53,
      "country_id": 1,
      "overview": "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
      "genres": "Action; Crime; Thriller",
      "director_name": "David Ayer",
      "budget": "40000000",
      "studios": "Cedar Park Entertainment; BlockFilm; Punch Palace Productions; Balboa Productions; Black Bear Pictures; Fifth Season; CAT5",
      "poster_url": "https://image.tmdb.org/t/p/w500/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg",
      "collection": null,
      "original_title": "A Working Man",
      "actors": "[{\"name\":\"Jason Statham\",\"character\":\"Levon Cade\"},{\"name\":\"Jason Flemyng\",\"character\":\"Wolo Kolisnyk\"},{\"name\":\"Merab Ninidze\",\"character\":\"Yuri\"},{\"name\":\"Maximilian Osinski\",\"character\":\"Dimi Kolisnyk\"},{\"name\":\"Cokey Falkow\",\"character\":\"Dougie\"},{\"name\":\"Michael Peña\",\"character\":\"Joe Garcia\"},{\"name\":\"David Harbour\",\"character\":\"Gunny Lefferty\"},{\"name\":\"Noemi Gonzalez\",\"character\":\"Carla Garcia\"},{\"name\":\"Arianna Rivas\",\"character\":\"Jenny Garcia\"},{\"name\":\"Isla Gie\",\"character\":\"Merry Cade\"}]"
  },
  {
      "movie_id": 91,
      "title": "Back in Action",
      "release_year": 2025,
      "runtime_minutes": 114,
      "rating": null,
      "box_office": null,
      "director_id": 87,
      "country_id": 1,
      "overview": "Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.",
      "genres": "Action; Comedy",
      "director_name": "Seth Gordon",
      "budget": null,
      "studios": "Chernin Entertainment; Exhibit A; Good One",
      "poster_url": "https://image.tmdb.org/t/p/w500/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/mkxGpqh4yOYqtENv01IrDcesFRf.jpg",
      "collection": null,
      "original_title": "Back in Action",
      "actors": "[{\"name\":\"Jamie Foxx\",\"character\":\"Matt\"},{\"name\":\"Cameron Diaz\",\"character\":\"Emily\"},{\"name\":\"McKenna Roberts\",\"character\":\"Alice\"},{\"name\":\"Rylan Jackson\",\"character\":\"Leo\"},{\"name\":\"Kyle Chandler\",\"character\":\"Chuck\"},{\"name\":\"Glenn Close\",\"character\":\"Ginny\"},{\"name\":\"Jamie Demetriou\",\"character\":\"Nigel\"},{\"name\":\"Andrew Scott\",\"character\":\"Baron\"},{\"name\":\"Fola Evans-Akingbola\",\"character\":\"Wendy\"},{\"name\":\"Robert Besta\",\"character\":\"Balthazar Gor\"}]"
  },
  {
      "movie_id": 30,
      "title": "Ballerina",
      "release_year": 2025,
      "runtime_minutes": 125,
      "rating": null,
      "box_office": "131794570.00",
      "director_id": 27,
      "country_id": 1,
      "overview": "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
      "genres": "Action; Thriller; Crime",
      "director_name": "Len Wiseman",
      "budget": "90000000",
      "studios": "Thunder Road; 87Eleven; Lionsgate",
      "poster_url": "https://image.tmdb.org/t/p/w500/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/sItIskd5xpiE64bBWYwZintkGf3.jpg",
      "collection": null,
      "original_title": "Ballerina",
      "actors": "[{\"name\":\"Ana de Armas\",\"character\":\"Eve\"},{\"name\":\"Keanu Reeves\",\"character\":\"John Wick\"},{\"name\":\"Ian McShane\",\"character\":\"Winston\"},{\"name\":\"Anjelica Huston\",\"character\":\"The Director\"},{\"name\":\"Gabriel Byrne\",\"character\":\"The Chancellor\"},{\"name\":\"Catalina Sandino Moreno\",\"character\":\"Lena\"},{\"name\":\"Ava McCarthy\",\"character\":\"Ella\"},{\"name\":\"Juliet Doherty\",\"character\":\"Tatiana\"},{\"name\":\"Norman Reedus\",\"character\":\"Daniel Pine\"},{\"name\":\"Lance Reddick\",\"character\":\"Charon\"}]"
  },
  {
      "movie_id": 61,
      "title": "Black Bag",
      "release_year": 2025,
      "runtime_minutes": 94,
      "rating": null,
      "box_office": "34985600.00",
      "director_id": 58,
      "country_id": 1,
      "overview": "When intelligence agent Kathryn Woodhouse is suspected of betraying the nation, her husband – also a legendary agent – faces the ultimate test of whether to be loyal to his marriage, or his country.",
      "genres": "Drama; Mystery; Thriller",
      "director_name": "Steven Soderbergh",
      "budget": "50000000",
      "studios": "Casey Silver Productions",
      "poster_url": "https://image.tmdb.org/t/p/w500/hHPovtU4b96LHcoeEwRkGHI5btw.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w500/gxO51FVgADhYGGnnRPIlutVqb30.jpg",
      "collection": null,
      "original_title": "Black Bag",
      "actors": "[{\"name\":\"Cate Blanchett\",\"character\":\"Kathryn St. Jean\"},{\"name\":\"Michael Fassbender\",\"character\":\"George Woodhouse\"},{\"name\":\"Tom Burke\",\"character\":\"Freddie Smalls\"},{\"name\":\"Marisa Abela\",\"character\":\"Clarissa Dubose\"},{\"name\":\"Regé-Jean Page\",\"character\":\"Col. James Stokes\"},{\"name\":\"Naomie Harris\",\"character\":\"Dr. Zoe Vaughn\"},{\"name\":\"Pierce Brosnan\",\"character\":\"Arthur Stieglitz\"},{\"name\":\"Kae Alexander\",\"character\":\"Anna Ko\"},{\"name\":\"Ambika Mod\",\"character\":\"Angela Childs\"},{\"name\":\"Gustaf Skarsgård\",\"character\":\"Philip Meacham\"}]"
  }
]
